import { SektorData } from "../../../shared/sektorData";
import { MODIFIER_MAX, MODIFIER_MIN } from "../../../shared/modifierLimits";
import { SEKTOR_SIZES } from "../../../shared/sektorSizes";
import { BuildingDefinition, BuildingFunction } from "../sektor/buildings/parseBuildingDefinitions";
import { createLocationPropertyMatrix } from "./locationPropertyMatrices";
import { RandomNumber } from "./randomNumber";

const REQUIREMENT_AMOUNT = 10;
// The player needs more ground than the bare solution stands on: room to put a building up and take
// it down again, room to make more of something than the least that will do, and room for whatever
// pays but was never asked for. Three times over is what leaves sektors as finishable under
// playtesting as they were back when every one of them was handed the whole hundred tiles.
const GROUND_TO_SPARE = 3;
// How much likelier a squeeze grows with every level, so that the highest levels are always squeezed.
const SQUEEZE_CHANCE_PER_LEVEL = 0.1;

// One way of making a resource: the building which makes it, and the one thing that building does
// to make it, which is what says how much of the resource it makes and what it takes to do so.
export interface ResourceProducer {
  buildingName: string;
  buildingFunction: BuildingFunction;
}

// One building of a sektor's solution: which building it is, what it stands there to make, how much
// of that the solution needs out of it, and the one thing it does to make it.
interface SolutionStep {
  buildingName: string;
  buildingFunction: BuildingFunction;
  resource: string;
  demand: number;
}

// Every resource some building makes, against the ways of making it.
export type ProductionGraph = Map<string, ResourceProducer[]>;

export type { RandomNumber };

// A sektor is generated by walking backwards from what it requires: at every layer a building which
// makes the current resource joins the palette, and one of that building's inputs becomes the next
// restriction. The walk therefore leaves behind a chain of buildings which, if the player places
// them, satisfies every restriction and produces what is required. The sektor is solvable because
// the walk built a solution, and nothing has to be simulated to know it.
export function createSektor(
  level: number,
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  negativeScoringResources: string[],
  randomNumber: RandomNumber = Math.random,
): SektorData {
  const productionGraph = buildProductionGraph(buildingDefinitions);
  const requiredResources = pickRequiredResources(
    productionGraph, [...localResources, ...negativeScoringResources], level, randomNumber
  );

  // What the walk leaves behind is the sektor's solution, and the ground the sektor needs is
  // measured against it; everything added afterwards is there to be looked at and ruled out.
  const restrictedResources = new Map<string, number>();
  const solutionSteps = requiredResources.flatMap(requiredResource =>
    walkBackwards(productionGraph, requiredResource, requiredResources, level, randomNumber, restrictedResources)
  );
  const paletteBuildingNames = new Set<string>(solutionSteps.map(solutionStep => solutionStep.buildingName));

  addAlternatives(productionGraph, restrictedResources, level, randomNumber, paletteBuildingNames);
  addDistractors(buildingDefinitions, level, randomNumber, paletteBuildingNames);
  addLocalResourceProducers(productionGraph, buildingDefinitions, localResources, randomNumber, paletteBuildingNames);

  const size = chooseSektorSize(solutionSteps, level, randomNumber);

  return {
    level,
    size,
    allowedBuildings: [...paletteBuildingNames],
    locationProperties: createLocationProperties(buildingDefinitions, paletteBuildingNames, level, size, randomNumber),
    importRestrictions: [...restrictedResources].map(([name, value]) => ({ name, value })),
    exportRequirements: requiredResources.map(name => ({ name, value: REQUIREMENT_AMOUNT })),
    buildings: [],
  };
}

// A building which does nothing makes nothing, so it never enters the graph. The destruction tool
// is such a building, which is why it is never part of a palette.
function buildProductionGraph(buildingDefinitions: BuildingDefinition[]): ProductionGraph {
  const productionGraph: ProductionGraph = new Map();

  for (const buildingDefinition of buildingDefinitions) {
    for (const buildingFunction of buildingDefinition.buildingFunctions) {
      for (const output of buildingFunction.outputs) {
        const producers = productionGraph.get(output.name) ?? [];
        producers.push({ buildingName: buildingDefinition.name, buildingFunction });
        productionGraph.set(output.name, producers);
      }
    }
  }

  return productionGraph;
}

// A local resource never leaves the sektor, so requiring an export of one would ask the player for
// something the rules of the sektor make impossible. A resource which scores against the player
// costs them for every unit they send out, so requiring one would punish them for finishing. A
// sektor asks only for what it is worth exporting.
function pickRequiredResources(
  productionGraph: ProductionGraph,
  unrequirableResources: string[],
  level: number,
  randomNumber: RandomNumber,
): string[] {
  const requirementCount = 1 + Math.floor(level / 2);
  // Every resource picked is taken out of the running, so no resource is required twice and the
  // picking ends even when every draw falls the same way.
  const producibleResources = [...productionGraph.keys()].filter(resource => !unrequirableResources.includes(resource));
  const requiredResources: string[] = [];

  while (requiredResources.length < requirementCount && producibleResources.length > 0) {
    const resource = pickRandom(producibleResources, randomNumber);
    requiredResources.push(resource);
    producibleResources.splice(producibleResources.indexOf(resource), 1);
  }

  return requiredResources;
}

// The walk goes as deep as the level asks for, but no deeper than the chain allows: it stops early
// when the current resource has no producer left, or when every input of the chosen producer is
// already restricted, is required, or is something no building makes and the player can simply
// import. What it returns is the chain it built: the buildings which, standing together, make what
// was required, each with the amount the layer above it asks of it.
function walkBackwards(
  productionGraph: ProductionGraph,
  requiredResource: string,
  requiredResources: string[],
  level: number,
  randomNumber: RandomNumber,
  restrictedResources: Map<string, number>,
): SolutionStep[] {
  const restrictionLayers = Math.min(1 + level, longestBackwardChain(productionGraph, requiredResource));
  const restrictionValue = Math.max(0, 4 - level);
  const solutionSteps: SolutionStep[] = [];

  let currentResource = requiredResource;
  // The topmost layer is there to meet the requirement, which is the whole of what is asked for.
  let currentDemand = REQUIREMENT_AMOUNT;
  // A restricted resource has a producer in the palette only because the layer below it puts one
  // there, so the walk goes one layer deeper than it restricts: whatever it restricts last is made
  // by the building it adds last. Stopping a layer earlier would hand the player a resource they
  // may not import and cannot make, which is the one thing the walk exists to prevent.
  for (let layer = 0; layer <= restrictionLayers; layer++) {
    const producers = productionGraph.get(currentResource);
    if (!producers || producers.length === 0) return solutionSteps;

    const producer = pickRandom(producers, randomNumber);
    const solutionStep = { ...producer, resource: currentResource, demand: currentDemand };
    solutionSteps.push(solutionStep);

    // This last building stands there to make what the layer above it may not import; restricting
    // one of its inputs in turn would leave that input with no producer of its own.
    if (layer === restrictionLayers) return solutionSteps;

    // A resource the sektor requires is already asked for in full, so capping what may be brought
    // in of it says nothing the requirement does not already say.
    const restrictableInputs = producer.buildingFunction.inputs
      .map(input => input.name)
      .filter(input =>
        productionGraph.has(input)
        && !restrictedResources.has(input)
        && !requiredResources.includes(input)
        && input !== currentResource
      );
    if (restrictableInputs.length === 0) return solutionSteps;

    const restrictedInput = pickRandom(restrictableInputs, randomNumber);
    restrictedResources.set(restrictedInput, restrictionValue);
    // Whatever this layer eats of the resource just restricted, over and above the little of it the
    // restriction still lets the player bring in, is what the layer below has to make.
    currentDemand = Math.max(0, inputAmount(producer.buildingFunction, restrictedInput) * copiesNeeded(solutionStep, level) - restrictionValue);
    currentResource = restrictedInput;
  }

  return solutionSteps;
}

function inputAmount(buildingFunction: BuildingFunction, resource: string): number {
  return buildingFunction.inputs.find(input => input.name === resource)?.value ?? 0;
}

// How many resources a walk backwards from here can restrict before it runs out of chain. The
// production graph has cycles — habitats make the work which staffs the wells which water the
// habitats — so a resource already on the path is never stepped on twice.
function longestBackwardChain(productionGraph: ProductionGraph, resource: string): number {
  function chainFrom(currentResource: string, path: string[]): number {
    let longest = path.length;
    for (const producer of productionGraph.get(currentResource) ?? []) {
      for (const input of producer.buildingFunction.inputs.map(input => input.name)) {
        if (!productionGraph.has(input) || path.includes(input)) continue;
        longest = Math.max(longest, chainFrom(input, [...path, input]));
      }
    }
    return longest;
  }

  return chainFrom(resource, [resource]);
}

// Another producer of a resource the player has to make locally is another way to succeed, so the
// lower the level the more of them the palette holds.
function addAlternatives(
  productionGraph: ProductionGraph,
  restrictedResources: Map<string, number>,
  level: number,
  randomNumber: RandomNumber,
  paletteBuildingNames: Set<string>,
) {
  const alternativeCount = Math.max(0, 3 - Math.floor(level / 2));

  for (const restrictedResource of restrictedResources.keys()) {
    const alternatives = (productionGraph.get(restrictedResource) ?? [])
      .map(producer => producer.buildingName)
      .filter(buildingName => !paletteBuildingNames.has(buildingName));

    for (let added = 0; added < alternativeCount && alternatives.length > 0; added++) {
      const buildingName = pickRandom(alternatives, randomNumber);
      paletteBuildingNames.add(buildingName);
      alternatives.splice(alternatives.indexOf(buildingName), 1);
    }
  }
}

// A building which helps with nothing still has to be looked at and ruled out, so the higher the
// level the more of them stand in the player's way.
function addDistractors(
  buildingDefinitions: BuildingDefinition[],
  level: number,
  randomNumber: RandomNumber,
  paletteBuildingNames: Set<string>,
) {
  const distractors = buildingDefinitions
    .filter(buildingDefinition => buildingDefinition.buildingFunctions.length > 0)
    .map(buildingDefinition => buildingDefinition.name)
    .filter(buildingName => !paletteBuildingNames.has(buildingName));

  for (let added = 0; added < level && distractors.length > 0; added++) {
    const buildingName = pickRandom(distractors, randomNumber);
    paletteBuildingNames.add(buildingName);
    distractors.splice(distractors.indexOf(buildingName), 1);
  }
}

// A restriction only caps what may be imported, so the walk hands the player a local route for
// whatever it restricts. A local resource is stricter than any restriction: it cannot be imported
// at all, at any level. So a building which consumes one is useless wherever nothing in the palette
// makes it — its functions simply starve — whether or not that resource was ever restricted. The
// producers added here can need local resources of their own, so this goes on until none is missing.
function addLocalResourceProducers(
  productionGraph: ProductionGraph,
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  randomNumber: RandomNumber,
  paletteBuildingNames: Set<string>,
) {
  for (;;) {
    const missingResource = findUnproducedLocalResource(buildingDefinitions, localResources, paletteBuildingNames);
    if (missingResource === undefined) return;

    const producers = (productionGraph.get(missingResource) ?? []).map(producer => producer.buildingName);
    // Nothing in the game makes it, so no palette can do anything about it.
    if (producers.length === 0) return;

    paletteBuildingNames.add(pickRandom(producers, randomNumber));
  }
}

function findUnproducedLocalResource(
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  paletteBuildingNames: Set<string>,
): string | undefined {
  const paletteFunctions = buildingDefinitions
    .filter(buildingDefinition => paletteBuildingNames.has(buildingDefinition.name))
    .flatMap(buildingDefinition => buildingDefinition.buildingFunctions);

  const producedResources = new Set(paletteFunctions.flatMap(buildingFunction => buildingFunction.outputs).map(output => output.name));

  return paletteFunctions
    .flatMap(buildingFunction => buildingFunction.inputs)
    .map(input => input.name)
    .find(resource => localResources.includes(resource) && !producedResources.has(resource));
}

// A sektor is given the smallest map its solution comfortably fits on, so that a chain of three
// buildings is not handed a field of tiles nobody will ever build on.
// That map is then squeezed one size down, the more often the higher the level, and twice as often
// again when the solution reads the ground: with tiles to spare every building simply goes on its
// best square and choosing where to build asks nothing of the player, whereas on a tight map the
// one location which suits two buildings can only be had by one of them. The squeeze never goes
// below the size the solution needs, so a squeezed sektor is still one which can be finished.
function chooseSektorSize(solutionSteps: SolutionStep[], level: number, randomNumber: RandomNumber): number {
  const neededTiles = solutionTileCount(solutionSteps, level);
  const comfortableSizeIndex = smallestSizeIndexFitting(neededTiles * GROUND_TO_SPARE);
  const tightestSizeIndex = smallestSizeIndexFitting(neededTiles);

  const squeezeChance = level * SQUEEZE_CHANCE_PER_LEVEL * (doesSolutionReadTheGround(solutionSteps) ? 2 : 1);
  const isSqueezed = randomNumber() < squeezeChance;

  const sizeIndex = isSqueezed ? Math.max(tightestSizeIndex, comfortableSizeIndex - 1) : comfortableSizeIndex;
  return SEKTOR_SIZES[sizeIndex].tilesPerSide;
}

// How much ground the solution stands on: every building of every chain, as many times over as it
// has to stand before it makes what the layer above it asks of it.
function solutionTileCount(solutionSteps: SolutionStep[], level: number): number {
  return solutionSteps.reduce((tiles, solutionStep) => tiles + copiesNeeded(solutionStep, level), 0);
}

// A building makes what it makes, so to make twice as much it has to stand twice. One standing
// there for something it turns out not to make at all still takes up its tile.
function copiesNeeded(solutionStep: SolutionStep, level: number): number {
  const amountPerBuilding = outputAmount(solutionStep, level);
  if (amountPerBuilding <= 0) return 1;
  return Math.max(1, Math.ceil(solutionStep.demand / amountPerBuilding));
}

// An output named after a location property is worth whatever the ground holds of it, and the
// poorest ground the sektor is made with is what the player can count on anywhere in it.
function outputAmount(solutionStep: SolutionStep, level: number): number {
  const producedOutput = solutionStep.buildingFunction.outputs.find(output => output.name === solutionStep.resource);
  if (!producedOutput) return 0;
  return producedOutput.value ?? (producedOutput.locationProperty === undefined ? 0 : propertyMinimum(level));
}

// A building whose output is drawn from the ground is worth more on one location than on another,
// which is what makes where it goes a choice. One whose output is simply written down is worth the
// same wherever it stands, and a solution built out of those has nothing to squeeze.
function doesSolutionReadTheGround(solutionSteps: SolutionStep[]): boolean {
  return solutionSteps
    .flatMap(solutionStep => solutionStep.buildingFunction.outputs)
    .some(output => output.locationProperty !== undefined);
}

// The smallest size with room for this many tiles. Nothing the game offers is bigger than the
// largest size, so a solution which outgrows even that is given the largest there is.
function smallestSizeIndexFitting(tiles: number): number {
  const sizeIndex = SEKTOR_SIZES.findIndex(sektorSize => sektorSize.tilesPerSide ** 2 >= tiles);
  return sizeIndex === -1 ? SEKTOR_SIZES.length - 1 : sizeIndex;
}

// A property the palette draws on is what the sektor is solved with, so its poorest location still
// holds something: the higher the level the less that is, but never nothing. Every other property
// is left to take any value it likes, having nothing to do with finishing the sektor.
function createLocationProperties(
  buildingDefinitions: BuildingDefinition[],
  paletteBuildingNames: Set<string>,
  level: number,
  size: number,
  randomNumber: RandomNumber,
): { [key: string]: number[][] } {
  const neededProperties = neededLocationProperties(buildingDefinitions, paletteBuildingNames);

  return Object.fromEntries(
    allLocationProperties(buildingDefinitions).map(propertyName => [
      propertyName,
      createLocationPropertyMatrix(
        propertyName,
        size,
        neededProperties.has(propertyName) ? propertyMinimum(level) : MODIFIER_MIN,
        randomNumber,
      ),
    ])
  );
}

// What the poorest location of a property the sektor is solved with still holds: the higher the
// level the less that is, but never nothing.
function propertyMinimum(level: number): number {
  return Math.max(1, MODIFIER_MAX - level);
}

function neededLocationProperties(buildingDefinitions: BuildingDefinition[], paletteBuildingNames: Set<string>): Set<string> {
  return new Set(
    locationPropertyNames(buildingDefinitions.filter(buildingDefinition => paletteBuildingNames.has(buildingDefinition.name)))
  );
}

function allLocationProperties(buildingDefinitions: BuildingDefinition[]): string[] {
  return [...new Set(locationPropertyNames(buildingDefinitions))];
}

function locationPropertyNames(buildingDefinitions: BuildingDefinition[]): string[] {
  return buildingDefinitions
    .flatMap(buildingDefinition => buildingDefinition.buildingFunctions)
    .flatMap(buildingFunction => buildingFunction.outputs)
    .map(output => output.locationProperty)
    .filter((propertyName): propertyName is string => propertyName !== undefined);
}

function pickRandom<Item>(items: Item[], randomNumber: RandomNumber): Item {
  return items[Math.floor(randomNumber() * items.length)];
}
