import { ResourceThroughput, SektorData } from "../../../shared/sektorData";
import { MODIFIER_MAX, MODIFIER_MIN } from "../../../shared/modifierLimits";
import { SEKTOR_SIZES } from "../../../shared/sektorSizes";
import { BuildingDefinition, BuildingFunction } from "../sektor/buildings/parseBuildingDefinitions";
import { createLocationPropertyMatrix } from "./locationPropertyMatrices";
import { ALTITUDE_PROPERTY } from "../../../shared/altitude";
import { createAltitudeMatrix } from "./altitudeMatrix";
import { propertiesShapedByAltitude } from "./altitudeEffects";
import { exportsOfThePlacedSolution } from "./solutionPlan";
import { RandomNumber } from "./randomNumber";

// How much of what the laid-out solution delivers the sektor actually asks for. A sektor of the
// lowest level asks for well under what its ground can give, so a player has room to place
// carelessly; the highest levels ask for nearly all of it, and only a solution placed about as well
// as it can be will do.
const SHARE_REQUIRED_AT_LOWEST_LEVEL = 0.4;
const SHARE_REQUIRED_GAINED_PER_LEVEL = 0.036;
const MOST_OF_THE_YIELD_REQUIRED = 0.9;
// A sektor which asks for nothing is no sektor at all. When its restrictions and its ground between
// them leave the solution unable to deliver anything, the restrictions are what gives: they are
// loosened a notch and the solution grown again, as many times as this allows.
const MOST_RESTRICTION_LOOSENINGS = 6;
// The largest map each of the first levels may be given, by its place in SEKTOR_SIZES. A level past
// the end of this may be given any size there is.
const LARGEST_SIZE_INDEX_BY_LEVEL = [1, 1, 2, 2, 2];
// Whether the sizes a sektor may be given are bounded by the level it is made for, which is what
// chooseSektorSize describes. Turn this off and every sektor is drawn from all the sizes whatever
// its level, which is the way to get maps of every size to look at.
const SIZE_SEKTORS_BY_LEVEL = true;

// One way of making a resource: the building which makes it, and the one thing that building does
// to make it, which is what says how much of the resource it makes and what it takes to do so.
export interface ResourceProducer {
  buildingName: string;
  buildingFunction: BuildingFunction;
}

// One layer of a sektor's solution: the building which makes the layer's resource. The layers of a
// chain feed one another, the first making what the sektor requires and each one after it making
// what the one before may not simply import.
interface SolutionLayer {
  buildingName: string;
  resource: string;
}

// The layers which together produce one required resource.
type SolutionChain = SolutionLayer[];

// Every resource some building makes, against the ways of making it.
export type ProductionGraph = Map<string, ResourceProducer[]>;

export type { RandomNumber };

// A sektor is generated by walking backwards from what it requires: at every layer a building which
// makes the current resource joins the palette, and one of that building's inputs becomes the next
// restriction. The walk therefore leaves behind a chain of buildings which, standing together,
// satisfies every restriction and produces what is required.
//
// The ground comes first and the asking comes last. The map is sized, its properties are laid out
// and its mountains are raised before anything is asked of the player, and only then is the chain
// laid out on that finished map and the sektor's requirements measured against what it delivers
// standing there. A requirement is therefore a thing some arrangement of buildings is known to
// deliver on this map, rather than a number which usually works out.
export function createSektor(
  level: number,
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  negativeScoringResources: string[],
  randomNumber: RandomNumber = Math.random,
): SektorData {
  const productionGraph = buildProductionGraph(buildingDefinitions);
  const requiredResources = pickRequiredResources(
    productionGraph, [...localResources, ...negativeScoringResources], level, randomNumber
  );

  const restrictedResources = new Map<string, number>();
  const chains = requiredResources.map(requiredResource =>
    walkBackwards(productionGraph, requiredResource, requiredResources, level, randomNumber, restrictedResources)
  );
  const paletteBuildingNames = new Set<string>(chains.flat().map(layer => layer.buildingName));

  addAlternatives(productionGraph, restrictedResources, level, randomNumber, paletteBuildingNames);
  addDistractors(buildingDefinitions, level, randomNumber, paletteBuildingNames);
  addLocalResourceProducers(productionGraph, buildingDefinitions, localResources, randomNumber, paletteBuildingNames);

  const size = chooseSektorSize(level, randomNumber);
  const allowedBuildings = [...paletteBuildingNames];
  const locationProperties = createLocationProperties(buildingDefinitions, paletteBuildingNames, level, size, randomNumber);

  // The restrictions can still be loosened by what follows, so they are read off afterwards.
  const exportRequirements = requirementsTheGroundCanMeet(
    requiredResources, restrictedResources, locationProperties, level,
    buildingDefinitions, allowedBuildings, localResources, negativeScoringResources,
  );

  return {
    level,
    size,
    allowedBuildings,
    locationProperties,
    importRestrictions: [...restrictedResources].map(([name, value]) => ({ name, value })),
    exportRequirements,
    buildings: [],
  };
}

// The solution is grown on the sektor's own ground and the sektor asks for a share of what it
// delivers standing there. Restrictions which leave it able to deliver nothing at all are loosened
// and the solution grown again, so that what comes back is always something to be done.
function requirementsTheGroundCanMeet(
  requiredResources: string[],
  restrictedResources: Map<string, number>,
  locationProperties: { [key: string]: number[][] },
  level: number,
  buildingDefinitions: BuildingDefinition[],
  allowedBuildings: string[],
  localResources: string[],
  negativeScoringResources: string[],
): ResourceThroughput[] {
  for (let loosening = 0; ; loosening++) {
    const deliveredExports = exportsOfThePlacedSolution(
      requiredResources,
      locationProperties,
      [...restrictedResources].map(([name, value]) => ({ name, value })),
      buildingDefinitions,
      allowedBuildings,
      localResources,
      negativeScoringResources,
    );

    const requirements = requiredResources
      .map(name => ({ name, value: amountRequired(deliveredExports.get(name) ?? 0, level) }))
      .filter(requirement => requirement.value > 0);

    if (requirements.length > 0) return requirements;

    // Nothing the sektor set out to ask for came through, and yet the solution standing on this
    // ground sends something out. A share of that is as good a thing to ask for: it is a thing
    // these buildings on these locations were seen to deliver, which is the whole of what a
    // requirement ever claims.
    const deliveredInstead = requirementsFromWhatWasDelivered(
      deliveredExports, restrictedResources, negativeScoringResources, level, requiredResources.length
    );
    if (deliveredInstead.length > 0) return deliveredInstead;

    if (loosening === MOST_RESTRICTION_LOOSENINGS) return [];

    for (const [name, value] of restrictedResources) restrictedResources.set(name, value + 1);
  }
}

// What the solution sends out which the sektor may ask for, most freely given first. A resource
// which scores against the player punishes them for finishing, and one the sektor caps the import
// of is already spoken for by that cap, so neither is ever asked for. A local resource never
// reaches here: it cannot leave the sektor, so it is no export of it.
function requirementsFromWhatWasDelivered(
  deliveredExports: Map<string, number>,
  restrictedResources: Map<string, number>,
  negativeScoringResources: string[],
  level: number,
  mostRequirements: number,
): ResourceThroughput[] {
  return [...deliveredExports]
    .filter(([name]) => !negativeScoringResources.includes(name) && !restrictedResources.has(name))
    .sort(([, amount], [, otherAmount]) => otherAmount - amount)
    .slice(0, mostRequirements)
    .map(([name, deliveredAmount]) => ({ name, value: amountRequired(deliveredAmount, level) }))
    .filter(requirement => requirement.value > 0);
}

// What the sektor asks for of a resource, out of what the solution laid out on its ground delivers.
// Always less than the whole of it at any level, so that there is some way of placing the solution
// other than the one way this worked out.
function amountRequired(deliveredAmount: number, level: number): number {
  const share = Math.min(
    MOST_OF_THE_YIELD_REQUIRED,
    SHARE_REQUIRED_AT_LOWEST_LEVEL + (level - 1) * SHARE_REQUIRED_GAINED_PER_LEVEL,
  );
  return Math.floor(deliveredAmount * share);
}

// A building which does nothing makes nothing, so it never enters the graph. The destruction tool
// is such a building, which is why it is never part of a palette.
function buildProductionGraph(buildingDefinitions: BuildingDefinition[]): ProductionGraph {
  const productionGraph: ProductionGraph = new Map();

  for (const buildingDefinition of buildingDefinitions) {
    for (const buildingFunction of buildingDefinition.buildingFunctions) {
      for (const output of buildingFunction.outputs) {
        const producers = productionGraph.get(output.name) ?? [];
        producers.push({ buildingName: buildingDefinition.name, buildingFunction });
        productionGraph.set(output.name, producers);
      }
    }
  }

  return productionGraph;
}

// A local resource never leaves the sektor, so requiring an export of one would ask the player for
// something the rules of the sektor make impossible. A resource which scores against the player
// costs them for every unit they send out, so requiring one would punish them for finishing. A
// sektor asks only for what it is worth exporting.
function pickRequiredResources(
  productionGraph: ProductionGraph,
  unrequirableResources: string[],
  level: number,
  randomNumber: RandomNumber,
): string[] {
  const requirementCount = 1 + Math.floor(level / 2);
  // Every resource picked is taken out of the running, so no resource is required twice and the
  // picking ends even when every draw falls the same way.
  const producibleResources = [...productionGraph.keys()].filter(resource => !unrequirableResources.includes(resource));
  const requiredResources: string[] = [];

  while (requiredResources.length < requirementCount && producibleResources.length > 0) {
    const resource = pickRandom(producibleResources, randomNumber);
    requiredResources.push(resource);
    producibleResources.splice(producibleResources.indexOf(resource), 1);
  }

  return requiredResources;
}

// The walk goes as deep as the level asks for, but no deeper than the chain allows: it stops early
// when the current resource has no producer left, or when every input of the chosen producer is
// already restricted, is required, or is something no building makes and the player can simply
// import. What it returns is the chain it built: the buildings which, standing together, make what
// was required. How much of it they make is not known here and is not guessed at — that is settled
// later, by laying the chain out on the sektor's own ground.
function walkBackwards(
  productionGraph: ProductionGraph,
  requiredResource: string,
  requiredResources: string[],
  level: number,
  randomNumber: RandomNumber,
  restrictedResources: Map<string, number>,
): SolutionChain {
  const restrictionLayers = Math.min(1 + level, longestBackwardChain(productionGraph, requiredResource));
  const restrictionValue = Math.max(0, 4 - level);
  const chain: SolutionChain = [];

  let currentResource = requiredResource;
  // A restricted resource has a producer in the palette only because the layer below it puts one
  // there, so the walk goes one layer deeper than it restricts: whatever it restricts last is made
  // by the building it adds last. Stopping a layer earlier would hand the player a resource they
  // may not import and cannot make, which is the one thing the walk exists to prevent.
  for (let layer = 0; layer <= restrictionLayers; layer++) {
    const producers = productionGraph.get(currentResource);
    if (!producers || producers.length === 0) return chain;

    const producer = pickRandom(producers, randomNumber);
    chain.push({ buildingName: producer.buildingName, resource: currentResource });

    // This last building stands there to make what the layer above it may not import; restricting
    // one of its inputs in turn would leave that input with no producer of its own.
    if (layer === restrictionLayers) return chain;

    // A resource the sektor requires is already asked for in full, so capping what may be brought
    // in of it says nothing the requirement does not already say.
    const restrictableInputs = producer.buildingFunction.inputs
      .map(input => input.name)
      .filter(input =>
        productionGraph.has(input)
        && !restrictedResources.has(input)
        && !requiredResources.includes(input)
        && input !== currentResource
      );
    if (restrictableInputs.length === 0) return chain;

    const restrictedInput = pickRandom(restrictableInputs, randomNumber);
    restrictedResources.set(restrictedInput, restrictionValue);
    currentResource = restrictedInput;
  }

  return chain;
}

// How many resources a walk backwards from here can restrict before it runs out of chain. The
// production graph has cycles — habitats make the work which staffs the wells which water the
// habitats — so a resource already on the path is never stepped on twice.
function longestBackwardChain(productionGraph: ProductionGraph, resource: string): number {
  function chainFrom(currentResource: string, path: string[]): number {
    let longest = path.length;
    for (const producer of productionGraph.get(currentResource) ?? []) {
      for (const input of producer.buildingFunction.inputs.map(input => input.name)) {
        if (!productionGraph.has(input) || path.includes(input)) continue;
        longest = Math.max(longest, chainFrom(input, [...path, input]));
      }
    }
    return longest;
  }

  return chainFrom(resource, [resource]);
}

// Another producer of a resource the player has to make locally is another way to succeed, so the
// lower the level the more of them the palette holds.
function addAlternatives(
  productionGraph: ProductionGraph,
  restrictedResources: Map<string, number>,
  level: number,
  randomNumber: RandomNumber,
  paletteBuildingNames: Set<string>,
) {
  const alternativeCount = Math.max(0, 3 - Math.floor(level / 2));

  for (const restrictedResource of restrictedResources.keys()) {
    const alternatives = (productionGraph.get(restrictedResource) ?? [])
      .map(producer => producer.buildingName)
      .filter(buildingName => !paletteBuildingNames.has(buildingName));

    for (let added = 0; added < alternativeCount && alternatives.length > 0; added++) {
      const buildingName = pickRandom(alternatives, randomNumber);
      paletteBuildingNames.add(buildingName);
      alternatives.splice(alternatives.indexOf(buildingName), 1);
    }
  }
}

// A building which helps with nothing still has to be looked at and ruled out, so the higher the
// level the more of them stand in the player's way.
function addDistractors(
  buildingDefinitions: BuildingDefinition[],
  level: number,
  randomNumber: RandomNumber,
  paletteBuildingNames: Set<string>,
) {
  const distractors = buildingDefinitions
    .filter(buildingDefinition => buildingDefinition.buildingFunctions.length > 0)
    .map(buildingDefinition => buildingDefinition.name)
    .filter(buildingName => !paletteBuildingNames.has(buildingName));

  for (let added = 0; added < level && distractors.length > 0; added++) {
    const buildingName = pickRandom(distractors, randomNumber);
    paletteBuildingNames.add(buildingName);
    distractors.splice(distractors.indexOf(buildingName), 1);
  }
}

// A restriction only caps what may be imported, so the walk hands the player a local route for
// whatever it restricts. A local resource is stricter than any restriction: it cannot be imported
// at all, at any level. So a building which consumes one is useless wherever nothing in the palette
// makes it — its functions simply starve — whether or not that resource was ever restricted. The
// producers added here can need local resources of their own, so this goes on until none is missing.
function addLocalResourceProducers(
  productionGraph: ProductionGraph,
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  randomNumber: RandomNumber,
  paletteBuildingNames: Set<string>,
) {
  for (;;) {
    const missingResource = findUnproducedLocalResource(buildingDefinitions, localResources, paletteBuildingNames);
    if (missingResource === undefined) return;

    const producers = (productionGraph.get(missingResource) ?? []).map(producer => producer.buildingName);
    // Nothing in the game makes it, so no palette can do anything about it.
    if (producers.length === 0) return;

    paletteBuildingNames.add(pickRandom(producers, randomNumber));
  }
}

function findUnproducedLocalResource(
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  paletteBuildingNames: Set<string>,
): string | undefined {
  const paletteFunctions = buildingDefinitions
    .filter(buildingDefinition => paletteBuildingNames.has(buildingDefinition.name))
    .flatMap(buildingDefinition => buildingDefinition.buildingFunctions);

  const producedResources = new Set(paletteFunctions.flatMap(buildingFunction => buildingFunction.outputs).map(output => output.name));

  return paletteFunctions
    .flatMap(buildingFunction => buildingFunction.inputs)
    .map(input => input.name)
    .find(resource => localResources.includes(resource) && !producedResources.has(resource));
}

// The map is made before anything is asked of the player, so there is no solution to measure it
// against. What a sektor's level settles is not which size it gets but which sizes it may get: the
// easiest levels are kept off the biggest maps, where a short chain would sit in a field of tiles
// nobody builds on, and from the sixth level on any size may come up. Within what the level allows
// the size is simply drawn, so that two sektors of a level are not the same shape of problem — a
// tight map, where the one location which suits two buildings can only be had by one of them, is a
// harder thing than a roomy one whatever the level.
function chooseSektorSize(level: number, randomNumber: RandomNumber): number {
  const largestSizeIndex = SIZE_SEKTORS_BY_LEVEL
    ? LARGEST_SIZE_INDEX_BY_LEVEL[Math.max(0, level - 1)] ?? SEKTOR_SIZES.length - 1
    : SEKTOR_SIZES.length - 1;

  return pickRandom(SEKTOR_SIZES.slice(0, largestSizeIndex + 1), randomNumber).tilesPerSide;
}

// A property the palette draws on is what the sektor is solved with, so its poorest location still
// holds something: the higher the level the less that is, but never nothing. Every other property
// is left to take any value it likes, having nothing to do with finishing the sektor.
function createLocationProperties(
  buildingDefinitions: BuildingDefinition[],
  paletteBuildingNames: Set<string>,
  level: number,
  size: number,
  randomNumber: RandomNumber,
): { [key: string]: number[][] } {
  const neededProperties = neededLocationProperties(buildingDefinitions, paletteBuildingNames);
  const altitudes = createAltitudeMatrix(size, level, randomNumber);

  // Every property is laid out over flat ground first and only then made to answer to the height it
  // lies at, so that what the ground is made of and how high it stands are two separate things.
  const propertyMatrices = Object.fromEntries(
    allLocationProperties(buildingDefinitions).map(propertyName => [
      propertyName,
      createLocationPropertyMatrix(
        propertyName,
        size,
        neededProperties.has(propertyName) ? propertyMinimum(level) : MODIFIER_MIN,
        randomNumber,
      ),
    ])
  );

  return {
    ...propertiesShapedByAltitude(propertyMatrices, altitudes),
    [ALTITUDE_PROPERTY]: altitudes,
  };
}


// What the poorest location of a property the sektor is solved with still holds: the higher the
// level the less that is, but never nothing.
function propertyMinimum(level: number): number {
  return Math.max(1, MODIFIER_MAX - level);
}

function neededLocationProperties(buildingDefinitions: BuildingDefinition[], paletteBuildingNames: Set<string>): Set<string> {
  return new Set(
    locationPropertyNames(buildingDefinitions.filter(buildingDefinition => paletteBuildingNames.has(buildingDefinition.name)))
  );
}

function allLocationProperties(buildingDefinitions: BuildingDefinition[]): string[] {
  return [...new Set(locationPropertyNames(buildingDefinitions))];
}

function locationPropertyNames(buildingDefinitions: BuildingDefinition[]): string[] {
  return buildingDefinitions
    .flatMap(buildingDefinition => buildingDefinition.buildingFunctions)
    .flatMap(buildingFunction => buildingFunction.outputs)
    .map(output => output.locationProperty)
    .filter((propertyName): propertyName is string => propertyName !== undefined);
}

function pickRandom<Item>(items: Item[], randomNumber: RandomNumber): Item {
  return items[Math.floor(randomNumber() * items.length)];
}
