import { ResourceThroughput, SektorData } from "../../../shared/sektorData";
import { MODIFIER_MAX } from "../../../shared/modifierLimits";
import { SEKTOR_SIZE } from "../../../shared/sektorSize";
import { BuildingDefinition, BuildingFunction } from "../sektor/buildings/parseBuildingDefinitions";
import { createLocationPropertyMatrix } from "./locationPropertyMatrices";
import { ALTITUDE_PROPERTY } from "../../../shared/altitude";
import { createAltitudeMatrix } from "./altitudeMatrix";
import { propertiesShapedByAltitude } from "./altitudeEffects";
import { exportsOfThePlacedSolution } from "./solutionPlan";
import { RandomNumber } from "./randomNumber";

// How much of what the laid-out solution delivers the sektor actually asks for. A sektor of the
// lowest level asks for well under what its ground can give, so a player has room to place
// carelessly; the highest levels ask for nearly all of it, and only a solution placed about as well
// as it can be will do.
const SHARE_REQUIRED_AT_LOWEST_LEVEL = 0.4;
const SHARE_REQUIRED_GAINED_PER_LEVEL = 0.036;
const MOST_OF_THE_YIELD_REQUIRED = 0.9;
// A sektor which asks for nothing is no sektor at all. When its restrictions and its ground between
// them leave the solution unable to deliver anything, the restrictions are what gives: they are
// loosened a notch and the solution grown again, as many times as this allows.
const MOST_RESTRICTION_LOOSENINGS = 6;

// One way of making a resource: the building which makes it, and the one thing that building does
// to make it, which is what says how much of the resource it makes and what it takes to do so.
export interface ResourceProducer {
  buildingName: string;
  buildingFunction: BuildingFunction;
}

// Every resource some building makes, against the ways of making it.
export type ProductionGraph = Map<string, ResourceProducer[]>;

export type { RandomNumber };

// A sektor is generated by walking backwards from what it requires: at every layer a building which
// makes the current resource is looked up, and one of that building's inputs becomes the next
// restriction. The walk therefore leaves behind restrictions which some chain of buildings,
// standing together, satisfies while producing what is required.
//
// The ground comes first and the asking comes last. The map is sized, its properties are laid out
// and its mountains are raised before anything is asked of the player, and only then is the chain
// laid out on that finished map and the sektor's requirements measured against what it delivers
// standing there. A requirement is therefore a thing some arrangement of buildings is known to
// deliver on this map, rather than a number which usually works out.
export function createSektor(
  level: number,
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  negativeScoringResources: string[],
  randomNumber: RandomNumber = Math.random,
): SektorData {
  const productionGraph = buildProductionGraph(buildingDefinitions);
  const requiredResources = pickRequiredResources(
    productionGraph, [...localResources, ...negativeScoringResources], level, randomNumber
  );

  const restrictedResources = new Map<string, number>();
  for (const requiredResource of requiredResources) {
    walkBackwards(productionGraph, requiredResource, requiredResources, level, randomNumber, restrictedResources);
  }

  const locationProperties = createLocationProperties(buildingDefinitions, level, randomNumber);

  // The restrictions can still be loosened by what follows, so they are read off afterwards.
  const exportRequirements = requirementsTheGroundCanMeet(
    requiredResources, restrictedResources, locationProperties, level,
    buildingDefinitions, localResources, negativeScoringResources,
  );

  return {
    level,
    locationProperties,
    importRestrictions: [...restrictedResources].map(([name, value]) => ({ name, value })),
    exportRequirements,
    buildings: [],
  };
}

// The solution is grown on the sektor's own ground and the sektor asks for a share of what it
// delivers standing there. Restrictions which leave it able to deliver nothing at all are loosened
// and the solution grown again, so that what comes back is always something to be done.
function requirementsTheGroundCanMeet(
  requiredResources: string[],
  restrictedResources: Map<string, number>,
  locationProperties: { [key: string]: number[][] },
  level: number,
  buildingDefinitions: BuildingDefinition[],
  localResources: string[],
  negativeScoringResources: string[],
): ResourceThroughput[] {
  for (let loosening = 0; ; loosening++) {
    const deliveredExports = exportsOfThePlacedSolution(
      requiredResources,
      locationProperties,
      [...restrictedResources].map(([name, value]) => ({ name, value })),
      buildingDefinitions,
      localResources,
      negativeScoringResources,
    );

    const requirements = requiredResources
      .map(name => ({ name, value: amountRequired(deliveredExports.get(name) ?? 0, level) }))
      .filter(requirement => requirement.value > 0);

    if (requirements.length > 0) return requirements;

    // Nothing the sektor set out to ask for came through, and yet the solution standing on this
    // ground sends something out. A share of that is as good a thing to ask for: it is a thing
    // these buildings on these locations were seen to deliver, which is the whole of what a
    // requirement ever claims.
    const deliveredInstead = requirementsFromWhatWasDelivered(
      deliveredExports, restrictedResources, negativeScoringResources, level, requiredResources.length
    );
    if (deliveredInstead.length > 0) return deliveredInstead;

    if (loosening === MOST_RESTRICTION_LOOSENINGS) return [];

    for (const [name, value] of restrictedResources) restrictedResources.set(name, value + 1);
  }
}

// What the solution sends out which the sektor may ask for, most freely given first. A resource
// which scores against the player punishes them for finishing, and one the sektor caps the import
// of is already spoken for by that cap, so neither is ever asked for. A local resource never
// reaches here: it cannot leave the sektor, so it is no export of it.
function requirementsFromWhatWasDelivered(
  deliveredExports: Map<string, number>,
  restrictedResources: Map<string, number>,
  negativeScoringResources: string[],
  level: number,
  mostRequirements: number,
): ResourceThroughput[] {
  return [...deliveredExports]
    .filter(([name]) => !negativeScoringResources.includes(name) && !restrictedResources.has(name))
    .sort(([, amount], [, otherAmount]) => otherAmount - amount)
    .slice(0, mostRequirements)
    .map(([name, deliveredAmount]) => ({ name, value: amountRequired(deliveredAmount, level) }))
    .filter(requirement => requirement.value > 0);
}

// What the sektor asks for of a resource, out of what the solution laid out on its ground delivers.
// Always less than the whole of it at any level, so that there is some way of placing the solution
// other than the one way this worked out.
function amountRequired(deliveredAmount: number, level: number): number {
  const share = Math.min(
    MOST_OF_THE_YIELD_REQUIRED,
    SHARE_REQUIRED_AT_LOWEST_LEVEL + (level - 1) * SHARE_REQUIRED_GAINED_PER_LEVEL,
  );
  return Math.floor(deliveredAmount * share);
}

// A building which does nothing makes nothing, so it never enters the graph. The destruction tool
// is such a building, which is why no sektor is ever built around it.
function buildProductionGraph(buildingDefinitions: BuildingDefinition[]): ProductionGraph {
  const productionGraph: ProductionGraph = new Map();

  for (const buildingDefinition of buildingDefinitions) {
    for (const buildingFunction of buildingDefinition.buildingFunctions) {
      for (const output of buildingFunction.outputs) {
        const producers = productionGraph.get(output.name) ?? [];
        producers.push({ buildingName: buildingDefinition.name, buildingFunction });
        productionGraph.set(output.name, producers);
      }
    }
  }

  return productionGraph;
}

// A local resource never leaves the sektor, so requiring an export of one would ask the player for
// something the rules of the sektor make impossible. A resource which scores against the player
// costs them for every unit they send out, so requiring one would punish them for finishing. A
// sektor asks only for what it is worth exporting.
function pickRequiredResources(
  productionGraph: ProductionGraph,
  unrequirableResources: string[],
  level: number,
  randomNumber: RandomNumber,
): string[] {
  const requirementCount = 1 + Math.floor(level / 2);
  // Every resource picked is taken out of the running, so no resource is required twice and the
  // picking ends even when every draw falls the same way.
  const producibleResources = [...productionGraph.keys()].filter(resource => !unrequirableResources.includes(resource));
  const requiredResources: string[] = [];

  while (requiredResources.length < requirementCount && producibleResources.length > 0) {
    const resource = pickRandom(producibleResources, randomNumber);
    requiredResources.push(resource);
    producibleResources.splice(producibleResources.indexOf(resource), 1);
  }

  return requiredResources;
}

// The walk goes as deep as the level asks for, but no deeper than the chain allows: it stops early
// when the current resource has no producer left, or when every input of the chosen producer is
// already restricted, is required, or is something no building makes and the player can simply
// import. What it leaves behind is the restrictions it set: what the player may not simply buy and
// has to make instead. How much of it can be made is not known here and is not guessed at — that is
// settled later, by laying a solution out on the sektor's own ground.
function walkBackwards(
  productionGraph: ProductionGraph,
  requiredResource: string,
  requiredResources: string[],
  level: number,
  randomNumber: RandomNumber,
  restrictedResources: Map<string, number>,
) {
  const restrictionLayers = Math.min(1 + level, longestBackwardChain(productionGraph, requiredResource));
  const restrictionValue = Math.max(0, 4 - level);

  let currentResource = requiredResource;
  // The walk goes one layer deeper than it restricts: whatever it restricts last is what the
  // building of the last layer makes. Stopping a layer earlier would hand the player a resource
  // they may not import and nothing makes, which is the one thing the walk exists to prevent.
  for (let layer = 0; layer <= restrictionLayers; layer++) {
    const producers = productionGraph.get(currentResource);
    if (!producers || producers.length === 0) return;

    const producer = pickRandom(producers, randomNumber);

    // This last building stands there to make what the layer above it may not import; restricting
    // one of its inputs in turn would leave that input with no producer of its own.
    if (layer === restrictionLayers) return;

    // A resource the sektor requires is already asked for in full, so capping what may be brought
    // in of it says nothing the requirement does not already say.
    const restrictableInputs = producer.buildingFunction.inputs
      .map(input => input.name)
      .filter(input =>
        productionGraph.has(input)
        && !restrictedResources.has(input)
        && !requiredResources.includes(input)
        && input !== currentResource
      );
    if (restrictableInputs.length === 0) return;

    const restrictedInput = pickRandom(restrictableInputs, randomNumber);
    restrictedResources.set(restrictedInput, restrictionValue);
    currentResource = restrictedInput;
  }
}

// How many resources a walk backwards from here can restrict before it runs out of chain. The
// production graph has cycles — habitats make the work which staffs the wells which water the
// habitats — so a resource already on the path is never stepped on twice.
function longestBackwardChain(productionGraph: ProductionGraph, resource: string): number {
  function chainFrom(currentResource: string, path: string[]): number {
    let longest = path.length;
    for (const producer of productionGraph.get(currentResource) ?? []) {
      for (const input of producer.buildingFunction.inputs.map(input => input.name)) {
        if (!productionGraph.has(input) || path.includes(input)) continue;
        longest = Math.max(longest, chainFrom(input, [...path, input]));
      }
    }
    return longest;
  }

  return chainFrom(resource, [resource]);
}

// Every building there is may be put up in the sektor, so every property some building draws on is
// one the sektor may be solved with, and each of them holds something even on its poorest location:
// the higher the level the less that is, but never nothing.
function createLocationProperties(
  buildingDefinitions: BuildingDefinition[],
  level: number,
  randomNumber: RandomNumber,
): { [key: string]: number[][] } {
  const altitudes = createAltitudeMatrix(randomNumber);

  // Every property is laid out over flat ground first and only then made to answer to the height it
  // lies at, so that what the ground is made of and how high it stands are two separate things.
  const propertyMatrices = Object.fromEntries(
    allLocationProperties(buildingDefinitions).map(propertyName => [
      propertyName,
      createLocationPropertyMatrix(propertyName, propertyMinimum(level), randomNumber),
    ])
  );

  return {
    ...propertiesShapedByAltitude(propertyMatrices, altitudes),
    [ALTITUDE_PROPERTY]: altitudes,
  };
}


// What the poorest location of a property the sektor is solved with still holds: the higher the
// level the less that is, but never nothing.
function propertyMinimum(level: number): number {
  return Math.max(1, MODIFIER_MAX - level);
}

function allLocationProperties(buildingDefinitions: BuildingDefinition[]): string[] {
  return [...new Set(locationPropertyNames(buildingDefinitions))];
}

function locationPropertyNames(buildingDefinitions: BuildingDefinition[]): string[] {
  return buildingDefinitions
    .flatMap(buildingDefinition => buildingDefinition.buildingFunctions)
    .flatMap(buildingFunction => buildingFunction.outputs)
    .map(output => output.locationProperty)
    .filter((propertyName): propertyName is string => propertyName !== undefined);
}

function pickRandom<Item>(items: Item[], randomNumber: RandomNumber): Item {
  return items[Math.floor(randomNumber() * items.length)];
}
